# --- Cổng 1883: Dành cho nội bộ
listener 1883
allow_anonymous true

# --- Cổng 8883: Mã hóa SSL/TLS
listener 8883
allow_anonymous true

# Đường dẫn đến chứng chỉ Let's Encrypt
cafile /etc/letsencrypt/live/mqtt.phucnguyen365.com/fullchain.pem
certfile /etc/letsencrypt/live/mqtt.phucnguyen365.com/fullchain.pem
keyfile /etc/letsencrypt/live/mqtt.phucnguyen365.com/privkey.pem

# Bật giao thức TLS v1.2+ để bảo mật cao nhất
tls_version tlsv1.2