# --- INTERNAL (Docker only) ---
listener 1883
allow_anonymous true

# --- PUBLIC (Internet) ---
listener 8883
allow_anonymous false
password_file /mosquitto/config/password_file

certfile /etc/letsencrypt/live/mqtt.phucnguyen365.com/fullchain.pem
keyfile /etc/letsencrypt/live/mqtt.phucnguyen365.com/privkey.pem

# --- BẢO VỆ CHỐNG SPAM & BRUTE-FORCE ---
# Giới hạn tổng số kết nối đồng thời trên port 8883
max_connections 500

# Giới hạn kích thước gói tin tối đa
message_size_limit 10240

# Ép ghi Log ra file để Fail2ban đọc
log_dest file /mosquitto/log/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information