listener 1883
allow_anonymous true

listener 8883
allow_anonymous true
cafile /etc/letsencrypt/live/mqtt.phucnguyen365.com/fullchain.pem
certfile /etc/letsencrypt/live/mqtt.phucnguyen365.com/fullchain.pem
keyfile /etc/letsencrypt/live/mqtt.phucnguyen365.com/privkey.pem
tls_version tlsv1.2